### PR TITLE
Simply add a Mongo DataSource, based on other implementations

### PR DESCRIPTION
**Pull request by Cafeinoman**
Just a missing implementation... Test passed, code style checked, Eclipse license signed.

### CODE REVIEW

**Comment by cescoffier** [comment]
Hum... classes are empty ?

**Comment by Cafeinoman** [comment]
Don't know what happened. Corrected.

**Comment by cescoffier** [comment]
Much better ! Thanks @Cafeinoman !

**Comment by cescoffier** [comment]
Thanks ! It's in !

**Pull request merged**
