### PR TITLE
Zookeeper Service Importer and Backend

### PR DESCRIPTION
**Pull request by cescoffier**
This PR provides 2 new components:

* Zookeeper Service Importer (Based on Apache Curator Service Discovery) imports services from Zookeeper using http://curator.apache.org/curator-x-discovery/
* Zookeeper service backend  stores service records in Zookeeper instead of a distributed map

### CODE REVIEW

**Comment by cescoffier** [comment]
@vietj @tsegismont @pmlopes Please review

**Comment by vietj** [comment]
curator seems to handle reconnect, however the service importer does not use curator and connect during `start` with `client.blockUntilConnected`. Shouldn't it handle reconnection as well ?

**Comment by cescoffier** [comment]
It actually does handle the reconnection. All async methods will attempt to connect / reconnect if not connected. The reconnect setting is configured in the configuration.

However, I should add a test for this to be sure it reconnect correctly.

**Comment by vietj** [comment]
@cescoffier is it handled by the service discovery or is it handled by ZK client ?

**Comment by cescoffier** [comment]
The client itself

**Comment by vietj** [comment]
ok, great :-)

**Comment by vietj** [comment]
LGTM

**Comment by vietj** [comment]
beside reconnect testing :-)

**Comment by cescoffier** [comment]
Yes exactly, I want to implement these 2 tests before merging. Will do that Today.

**Pull request merged**
