### PR TITLE
Performance issue

### PR DESCRIPTION
**Pull request by robertonav20**
Add new method for save the record by an uuid string passed by user

Add new method for read the record by an uuid string passed by user

### CODE REVIEW

**Comment by tsegismont** [comment]
It seems there are test failures, can you look into it?

**Comment by robertonav20** [comment]
Hi,
i ve build the entire project locally and i haven't test failure with jdk 1.8

testReconnection of ZookeeperBackendServiceTest -> it's ok on my local pc
image

testInsertionOfMultipleRecords of ServiceDiscoveryBackendTest -> it's ok on my local pc
image

Can you help me?

**Comment by robertonav20** [comment]
I adjust my method and now the ci build failed with the same result of yesterday build at this link https://github.com/vert-x3/vertx-service-discovery/actions/runs/747028260

Maybe the latest version 4.1.0-SNAPSHOT is unstable, maybe could i use the latest stable version ?

**Comment by tsegismont** [comment]
@robertonav20 yeah sorry I had not noticed it was an intermittent failure on CI, unrelated to your PR

**Review by tsegismont — COMMENTED** [review]
Thank you for the PR @robertonav20 

We do not need alternative storage methods. When you store a record, you get a uuid already (`Record.getRegistration()`).

We lack a way to lookup a record by this `uuid` (although it is possible to unpublish a record by uuid)

Can you modify the PR to keep only the additional lookup method? Thank you

**Comment by robertonav20** [comment]
Hi @tsegismont
thanks for your answer but i don't understand why i need to remove the new store method.
That method is totally optional so the user can choose if use it or not and with this method the user can create his unique key for user business logic store/read operation of the records from vertx.

**Comment by tsegismont** [comment]
Because I don't want to maintain two ways of doing the same thing.

Alternatively, you could create a wrapper of `DiscoveryImpl` to intercept calls to `store` method and insert your own logic.

**Comment by robertonav20** [comment]
Hi,
i understand your reason, but it dont understand your solution "Alternatively, you could create a wrapper of DiscoveryImpl to intercept calls to store method and insert your own logic."

Can you explain it ? Can you help me?
Thanks in advance.

**Comment by tsegismont** [comment]
I meant that you could create your own implementation of `ServiceDiscovery`. Your class would extend `DiscoveryImpl` you could add the storage method you want.

**Comment by robertonav20** [comment]
Hi @tsegismont,
so you suggest just extend DiscoveryImpl but this solution isn't enough to store the record because i must use backend for put record and we know the random uuid will be used. For this reason i must extend DiscoveryImpl and DefaultServiceDiscoveryBackend or implement the 2 interfaces ServiceDiscovery and ServiceDiscoveryBackend for to reach the goal.
Against to leave the user make this job i think could be better decision add an if to the store method with check if the registration string of the record exist or not and in this case use uuid random string, so with this logic we can manage all use case.
You can see the last commit runned successfully with tests on ci.

I just help the project because i saw the problem on read operation like i explain it before.
I don't want to impose my idea, maybe you have many reasons not to accept this logic that I don't know. 
I'm hope to understand.

Thanks in advance

**Comment by robertonav20** [comment]
Someone can help me?

**Comment by vietj** [comment]
ping @tsegismont

**Comment by robertonav20** [comment]
@vietj can you answer me at my last comment?

Thank you in advance!

**Comment by tsegismont** [comment]
Superseded by #151

**Comment by tsegismont** [comment]
@robertonav20 thanks for sharing a PR. I prefer not to take the changes for the reasons explained above.

**Pull request closed without merging**
